apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-9090
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/silvacharles/kubernetes-lab.git
    targetRevision: HEAD
    path: nginx-argocd/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
