apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 9090;

        location / {
            default_type text/html;
            return 200 "<h1>Nginx rodando na porta 9090!</h1>";
        }
    }
